-- Business Question 14: What proportion of net revenue is generated by repeat customers vs single-order customers?
-- Purpose: Evaluates customer retention revenue concentration and loyalty value creation.

WITH customer_order_counts AS (
    SELECT 
        customer_id,
        COUNT(DISTINCT transaction_id) AS lifetime_orders,
        SUM(revenue) AS lifetime_revenue,
        SUM(gross_profit) AS lifetime_gross_profit
    FROM fact_transactions
    GROUP BY customer_id
)
SELECT 
    CASE 
        WHEN lifetime_orders = 1 THEN 'Single-Order Customer'
        WHEN lifetime_orders BETWEEN 2 AND 5 THEN 'Repeat Customer (2-5 Orders)'
        ELSE 'Loyal Customer (6+ Orders)'
    END AS customer_retention_tier,
    COUNT(customer_id) AS customer_count,
    ROUND(SUM(lifetime_revenue), 2) AS total_revenue_inr,
    ROUND(SUM(lifetime_revenue) * 100.0 / SUM(SUM(lifetime_revenue)) OVER (), 2) AS revenue_share_pct,
    ROUND(SUM(lifetime_gross_profit), 2) AS total_gross_profit_inr,
    ROUND((SUM(lifetime_gross_profit) / NULLIF(SUM(lifetime_revenue), 0)) * 100, 2) AS gross_margin_pct
FROM customer_order_counts
GROUP BY 1
ORDER BY total_revenue_inr DESC;
